# Generated by Django 3.1.3 on 2020-12-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodeapp', '0002_post_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_data',
            field=models.CharField(default=models.CharField(max_length=50), max_length=500),
        ),
    ]
