# Generated by Django 3.1.3 on 2020-12-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodeapp', '0003_post_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='test_data',
            field=models.CharField(max_length=500),
        ),
    ]
