# Generated by Django 3.1.3 on 2020-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodeapp', '0004_auto_20201213_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
