# Generated by Django 3.1.3 on 2020-12-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodeapp', '0006_auto_20201216_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uthora',
            new_name='author',
        ),
    ]
